### PR TITLE
Use hidden folder on Linux

### PR DESCRIPTION
**Pull request by orschiro**
Minor correction.

Thank you for this great tool! :-)

### CODE REVIEW

**Comment by Rapti** [comment]
What happens if there's already a non-hidden folder? Will it be moved?

**Comment by orschiro** [comment]
@Rapti I don't think it will be moved.

**Comment by fabianonline** [comment]
Sorry for the delay in answering to this... If I read the code correctly, all this PR does is changing the README, not the actual code... doesn't it?

**Comment by orschiro** [comment]
yep, that's correct!

**Comment by fabianonline** [comment]
Thanks. I didn't realize the default in the code was already .telegram_backup.

**Comment by orschiro** [comment]
Welcome! :-)

**Pull request merged**
